export default async () => {
	try {
		// let data = await fetch('http://localhost:5000/').then(res => res.json())
		// console.log(data)
	} catch (err) {
		console.log('something went wrong', err)
	}
}
